### ISSUE TITLE
TODO v1.0.0

### ISSUE THREAD

**Issue by adigitoleo** [adigitoleo/vim-mellow-statusline#1]
- [x] ~~Outdated plugin notifier: like auracle for AUR, but for vim-plug instead? Use async support to run the git fetches?~~ Out of scope
- [x] ~~Keyboard input/locale hints: integrate xkb-switch indicator?~~ No, this is a job for the window manager / global statusbar
- [x] Fix mode indicator not being removed when special buffers (netrw, quickfix, ...) lose focus [Can't repro, open new issue if encountered]
- [x] ~~Tabline integration (subject to requests)~~ Out of scope
- [x] ~~Green color for ALE when no errors or warnings found~~ Linter status is hidden when no errors or warnings are found
- [x] ~~Add working directory indicator (useful when using neovim's `:lcd`)~~ Nah, improve the custom info field later instead
- [x] Add generic diagnostic indicator (incl. custom color support)
- [x] Refactor ALE diagnostic parser to use the generic indicator
- [x] Refactor indent/noexpandtab indicator to use the generic indicator
- [x] Add trailing whitespace diagnostic
- [x] Add options to toggle all of the default diagnostic indicators
- [x] Add buffer number display to File component
- [x] Add option to toggle buffer number display
- [x] ~~Refactor MellowDiagnosticFunction to use the new generic indicator function~~ Removed MellowDiagnosticFunction
- [x] Add helpfile and review documentation

**Comment by adigitoleo** [comment]
A couple of small things to do before release:
- Add a CHANGELOG.md
- Test the custom component CoC status example from the helpfile

**Comment by adigitoleo** [comment]
https://github.com/adigitoleo/vim-mellow-statusline/tree/v1.0.0
